# Generated by Django 5.2.8 on 2025-11-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSession',
            new_name='AcademicPeriod',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='exam',
            new_name='academic_period',
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'academic_period')},
        ),
        migrations.CreateModel(
            name='GradingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.IntegerField()),
                ('upper_bound', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('subject', models.ForeignKey(blank=True, help_text='Leave blank for global grading.', null=True, on_delete=django.db.models.deletion.CASCADE, to='resultsapp.subject')),
            ],
            options={
                'ordering': ['-upper_bound'],
                'unique_together': {('subject', 'lower_bound', 'upper_bound')},
            },
        ),
    ]
