# Generated by Django 5.2.8 on 2025-11-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0002_rename_examsession_academicperiod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingstructure',
            options={'ordering': ['-max_score']},
        ),
        migrations.RenameField(
            model_name='gradingstructure',
            old_name='lower_bound',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='gradingstructure',
            old_name='upper_bound',
            new_name='min_score',
        ),
        migrations.AlterUniqueTogether(
            name='gradingstructure',
            unique_together={('subject', 'min_score', 'max_score')},
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultsapp.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
