# Generated by Django 5.2.8 on 2025-11-19 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0003_alter_gradingstructure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolAdmin',
            new_name='SchoolAdministrator',
        ),
    ]
